---
# tasks file for dhcp_pxe

#  Указание файла с дополнителыми переменными (понадобится при добавлении темплейтов)
#  vars_files:
#  - defaults/main.yml

- include_tasks: web.yml

- include_tasks: tftp.yml

- include_tasks: dhcp.yml
